-- Event Table
CREATE TABLE Event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER REFERENCES GroupTable(id) ON UPDATE CASCADE ON DELETE CASCADE,
    creator_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    title VARCHAR(20),
    description TEXT,
    event_time TIMESTAMP,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- EventResponse Table
CREATE TABLE EventResponse (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id INTEGER REFERENCES Event(id) ON UPDATE CASCADE ON DELETE CASCADE,
    user_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    response_id INTEGER REFERENCES EventOptions(id) ON UPDATE CASCADE ON DELETE CASCADE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE EventOptions {
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id INTEGER REFERENCES Event(id) ON UPDATE CASCADE ON DELETE CASCADE,
    option_name VARCHAR(100)
}