-- Notification Table
CREATE TABLE Notification (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    sender_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    notification_type VARCHAR(16),
    group_id INTEGER REFERENCES GroupTable(id) ON UPDATE CASCADE ON DELETE CASCADE,
    event_id INTEGER REFERENCES Event(id) ON UPDATE CASCADE ON DELETE CASCADE,
    is_read BOOLEAN DEFAULT FALSE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

