-- UserChat Table
CREATE TABLE UserChat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sender_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    receiver_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    message TEXT,
    image_id INTEGER REFERENCES Image(id) ON UPDATE CASCADE ON DELETE CASCADE,
    is_read BOOLEAN DEFAULT FALSE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- GroupChat Table
CREATE TABLE GroupChat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER REFERENCES GroupTable(id) ON UPDATE CASCADE ON DELETE CASCADE,
    sender_id INTEGER REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    message TEXT,
    image_id INTEGER REFERENCES Image(id) ON UPDATE CASCADE ON DELETE CASCADE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);